spring:
  application:
    name: kotlin-currency-accounts
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml

configuration:
  exchange:
    service:
      url: http://api.nbp.pl/api/exchangerates/rates/a/USD/
